niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 w2v.py
Traceback (most recent call last):
  File "w2v.py", line 58, in <module>
    model1 = Word2Vec(data, size=200, window=5, min_count=3, workers=0)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 630, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 801, in build_vocab
    sentences, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1487, in scan_vocab
    vocab[word] += 1
TypeError: unhashable type: 'list'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 w2v.py
^[[ATraceback (most recent call last):
  File "w2v.py", line 58, in <module>
    model1 = Word2Vec(data, size=200, window=5, min_count=3, workers=0)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 630, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 801, in build_vocab
    sentences, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1487, in scan_vocab
    vocab[word] += 1
TypeError: unhashable type: 'list'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ clear

niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 w2v.py
Traceback (most recent call last):
  File "w2v.py", line 54, in <module>
    data = trainingdata
NameError: name 'trainingdata' is not defined
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 w2v.py
Traceback (most recent call last):
  File "w2v.py", line 55, in <module>
    model1 = Word2Vec(data, size=200, window=5, min_count=3, workers=0)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 630, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 801, in build_vocab
    sentences, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1487, in scan_vocab
    vocab[word] += 1
TypeError: unhashable type: 'list'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 w2v.py
Traceback (most recent call last):
  File "w2v.py", line 55, in <module>
    model1 = Word2Vec(data, size=200, window=5, min_count=3, workers=0)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 630, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 801, in build_vocab
    sentences, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1487, in scan_vocab
    vocab[word] += 1
TypeError: unhashable type: 'list'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 w2v.py
Traceback (most recent call last):
  File "w2v.py", line 55, in <module>
    model1 = Word2Vec(data, size=200, window=5, min_count=3, workers=0)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 630, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 801, in build_vocab
    sentences, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1487, in scan_vocab
    vocab[word] += 1
TypeError: unhashable type: 'list'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Word2Vec-checkpoint.py [A
Traceback (most recent call last):
  File "Word2Vec-checkpoint.py", line 41, in <module>
    model1 = Word2Vec(data, size=200, window=5, min_count=3, workers=4)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 630, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 801, in build_vocab
    sentences, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1487, in scan_vocab
    vocab[word] += 1
TypeError: unhashable type: 'list'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Word2Vec.py
^[[A^[[A^[[A^[[A^[[BTraceback (most recent call last):
  File "Word2Vec.py", line 62, in <module>
    model1 = Word2Vec(data, size=200, window=5, min_count=3, workers=4)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 630, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 801, in build_vocab
    sentences, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1487, in scan_vocab
    vocab[word] += 1
TypeError: unhashable type: 'list'
^[[Bniranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python Word2Vec.py
Traceback (most recent call last):
  File "Word2Vec.py", line 62, in <module>
    model1 = Word2Vec(data, size=200, window=5, min_count=3, workers=4)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 748, in __init__
    fast_version=FAST_VERSION)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 630, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 801, in build_vocab
    sentences, progress_per=progress_per, trim_rule=trim_rule)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1487, in scan_vocab
    vocab[word] += 1
TypeError: unhashable type: 'list'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python cleaning_repairs.py 
Traceback (most recent call last):
  File "cleaning_repairs.py", line 42, in <module>
    data = Read_Train_Data(config)
  File "cleaning_repairs.py", line 31, in Read_Train_Data
    row[0] = re.sub('[^a-zA-Z]!""#$%&()*+,-./:;<=>?@[\\]^_`{|}', ' ', row[0])
  File "/home/niranjan/anaconda3/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/niranjan/anaconda3/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 619, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 19
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python cleaning_repairs.py 
Traceback (most recent call last):
  File "cleaning_repairs.py", line 66, in <module>
    test_word = Read_Test_Data(config)
  File "cleaning_repairs.py", line 53, in Read_Test_Data
    if is_csv:
NameError: name 'is_csv' is not defined
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python cleaning_repairs.py 
Traceback (most recent call last):
  File "cleaning_repairs.py", line 66, in <module>
    test_word = Read_Test_Data(config)
  File "cleaning_repairs.py", line 53, in Read_Test_Data
    if is_csv:
NameError: name 'is_csv' is not defined
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python cleaning_repairs.py 
Traceback (most recent call last):
  File "cleaning_repairs.py", line 66, in <module>
    test_word = Read_Test_Data(config)
  File "cleaning_repairs.py", line 57, in Read_Test_Data
    keys = re.sub('[^a-zA-Z]!""#$%&()*+,-./:;<=>?@[\\]^_`{|}', ' ', row[0])
  File "/home/niranjan/anaconda3/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/niranjan/anaconda3/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 619, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 19
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python cleaning_repairs.py 
Traceback (most recent call last):
  File "cleaning_repairs.py", line 69, in <module>
    test_word = Read_Test_Data(config)
  File "cleaning_repairs.py", line 60, in Read_Test_Data
    keys = re.sub('[^a-zA-Z]!""#$%&()*+,-./:;<=>?@[\\]^_`{|}', ' ', row[0])
  File "/home/niranjan/anaconda3/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/niranjan/anaconda3/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 619, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 19
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python cleaning_repairs.py 
Traceback (most recent call last):
  File "cleaning_repairs.py", line 69, in <module>
    test_word = Read_Test_Data(config)
  File "cleaning_repairs.py", line 60, in Read_Test_Data
    keys = re.sub('[^a-zA-Z]!""#$%&()*+,-./:;<=>?@', ' ', row[0])
  File "/home/niranjan/anaconda3/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/niranjan/anaconda3/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/home/niranjan/anaconda3/lib/python3.6/sre_parse.py", line 619, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 19
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py 
Traceback (most recent call last):
  File "Preprocess.py", line 68, in <module>
    data = Read_Train_Data(config)
  File "Preprocess.py", line 55, in Read_Train_Data
    reader = csv.reader(f)
NameError: name 'csv' is not defined
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py 
loading the trainingdata...
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 16, in Read_WordVec
    with open(config.vec_file, 'r') as fvec:
FileNotFoundError: [Errno 2] No such file or directory: 'Data/vec_3.txt'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py 
loading the trainingdata...
a
the
and
with
this
.
.
.
clarette
alr
tracolla
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 39, in Read_WordVec
    assert len(wordLS) == config.vocab_size
AssertionError
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py 
loading the trainingdata...
a
the
and
with
this
.
.
.
clarette
alr
tracolla
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 42, in Read_WordVec
    cPickle.dump(word_vec, open('word_vec.pkl','w'), protocol=cPickle.HIGHEST_PROTOCOL)
AttributeError: module '_pickle' has no attribute 'HIGHEST_PROTOCOL'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py 
loading the trainingdata...
a
the
and
with
this
.
.
.
alr
tracolla
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 42, in Read_WordVec
    cPickle.dump(word_vec, open('word_vec.pkl','w'))
TypeError: write() argument must be str, not bytes
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py 
loading the trainingdata...
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 40, in Read_WordVec
    word_vec = np.array(vec_ls, dtype=np.float32)
ValueError: setting an array element with a sequence.
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py 
loading the trainingdata...
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 16, in Read_WordVec
    with open(config.vec_file, 'r') as fvec:
FileNotFoundError: [Errno 2] No such file or directory: 'Data/vec_3.txt'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 40, in Read_WordVec
    word_vec = np.array(vec_ls, dtype=np.float32)
ValueError: setting an array element with a sequence.
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 42, in Read_WordVec
    cPickle.dump(word_vec, open('word_vec.pkl','w'))
TypeError: write() argument must be str, not bytes
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
Traceback (most recent call last):
  File "Preprocess.py", line 96, in <module>
    vocab, _ = Read_WordVec(config)
  File "Preprocess.py", line 42, in Read_WordVec
    cPickle.dump(word_vec, open('word_vec.pkl','w'))
TypeError: write() argument must be str, not bytes
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
Traceback (most recent call last):
  File "Preprocess.py", line 99, in <module>
    test_word = Read_Test_Data(config)
  File "Preprocess.py", line 80, in Read_Test_Data
    if is_csv:
NameError: name 'is_csv' is not defined
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
data has 18885 document, size of word vocabular: 7638.
Traceback (most recent call last):
  File "Preprocess.py", line 145, in <module>
    for step, (x, y, mask, key_words) in enumerate(data_iterator(train_data, config.batch_size, config.num_steps)):
  File "Preprocess.py", line 117, in data_iterator
    tmp.append(word_to_idx[wd])
TypeError: unhashable type: 'list'
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
^Cloading the trainingdata...
Traceback (most recent call last):
  File "Preprocess.py", line 94, in <module>
    print('loading the trainingdata...')
KeyboardInterrupt
^C
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
data has 1 document, size of word vocabular: 7638.
Traceback (most recent call last):
  File "Preprocess.py", line 167, in <module>
    print('total step: ',step)
NameError: name 'step' is not defined
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
  File "Preprocess.py", line 167
    print 'total step: ',step
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('total step: ',step)?
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
  File "Preprocess.py", line 167
    print 'total step: ',step
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('total step: ',step)?
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
data has 1 document, size of word vocabular: 7638.
Traceback (most recent call last):
  File "Preprocess.py", line 167, in <module>
    print ('total step: ',step)
NameError: name 'step' is not defined
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python Preprocess.py
  File "Preprocess.py", line 167
    print 'total step: ',step
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('total step: ',step)?
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python Preprocess.py
  File "Preprocess.py", line 170
    print 'total step: ',step
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('total step: ',step)?
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
data has 1 document, size of word vocabular: 7638.
Traceback (most recent call last):
  File "Preprocess.py", line 169, in <module>
    print('total step: ',step )
NameError: name 'step' is not defined
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Preprocess.py
loading the trainingdata...
data has 1 document, size of word vocabular: 7638.
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 T
TM-AUTO-2(1).py  Train.py         
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Train.py
Traceback (most recent call last):
  File "Train.py", line 24, in <module>
    word_vec = cPickle.load(open('word_vec.pkl', 'r'))
  File "/home/niranjan/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ python3 Train.py
2018-09-06 10:54:30.891579: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f2237547978>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:From Train.py:90: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 120 and 70 for 'model/RNN/RNN_sentence/RNN_sentence/multi_rnn_cell/cell_0/lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [32,120], [70,240].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Train.py", line 263, in <module>
    tf.app.run()
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "Train.py", line 238, in main
    m = Model(is_training=True, config=config, filename='coverage_data')
  File "Train.py", line 125, in __init__
    (cell_output, state) = cell(tf.concat([inputs[:, time_step, :], mt], axis=1), state)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 232, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1292, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1099, in __call__
    output, new_state = self._cell(inputs, state, scope=scope)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 339, in __call__
    *args, **kwargs)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 833, in call
    array_ops.concat([inputs, m_prev], 1), self._kernel)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2122, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4279, in mat_mul
    name=name)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/niranjan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 120 and 70 for 'model/RNN/RNN_sentence/RNN_sentence/multi_rnn_cell/cell_0/lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [32,120], [70,240].
niranjan@Niranjan-PC /media/niranjan/New Volume/Text Marcato/TM_MTA_LSTM $ ~~


